=== CloudlyIO/open-mplane/fb-oru/tif/shared/dtd/RegMap.dtd
<!-- DTD For device register map definitions -->

<!ELEMENT RegisterMap (xinclude:include|Device)*>
<!ATTLIST RegisterMap version CDATA #REQUIRED>
<!ATTLIST RegisterMap xmlns:html CDATA "http://www.w3.org/TR/REC-html40">
<!ATTLIST RegisterMap xmlns:xinclude CDATA "http://www.w3.org/2001/XInclude">

<!ELEMENT Device (Constants|Ranges|Region|Feature|xinclude:include)*>
<!ATTLIST Device name ID #REQUIRED>
<!ATTLIST Device width CDATA "16">
<!ATTLIST Device comment CDATA #IMPLIED>

<!ELEMENT Constants (Const|xinclude:include)*>

<!ELEMENT Const (#PCDATA)>
<!ATTLIST Const name ID #REQUIRED>
<!ATTLIST Const comment CDATA #REQUIRED>

<!ELEMENT Ranges (Range|xinclude:include)*>

<!ELEMENT Range EMPTY>
<!ATTLIST Range name ID #REQUIRED>
<!ATTLIST Range comment CDATA #REQUIRED>
<!ATTLIST Range begin CDATA #REQUIRED>
<!ATTLIST Range end CDATA #REQUIRED>

<!ELEMENT Region (xinclude:include|Field|Region|Alias|Combine)*>
<!ATTLIST Region name ID #REQUIRED>
<!ATTLIST Region base CDATA "0">
<!ATTLIST Region comment CDATA #IMPLIED>

<!-- <!ELEMENT Feature (xinclude:include|Field|Region|FieldName|Alias|Combine)*> -->
<!ELEMENT Feature (xinclude:include|FieldName)*>
<!ATTLIST Feature name ID #REQUIRED>
<!ATTLIST Feature comment CDATA #REQUIRED>

<!ELEMENT Field EMPTY>
<!ATTLIST Field name ID #REQUIRED>
<!ATTLIST Field comment CDATA #REQUIRED>
<!ATTLIST Field offset CDATA #REQUIRED>
<!ATTLIST Field bitmap CDATA #IMPLIED>
<!ATTLIST Field start CDATA #IMPLIED>
<!ATTLIST Field numbits CDATA "1">
<!ATTLIST Field default CDATA #IMPLIED>
<!ATTLIST Field access (read-write|write-only|read-only) "read-write">

<!ELEMENT Alias (#PCDATA)>
<!ATTLIST Alias name ID #REQUIRED>
<!ATTLIST Alias comment CDATA #REQUIRED>

<!ELEMENT Combine (Bits)*>
<!ATTLIST Combine name ID #REQUIRED>
<!ATTLIST Combine comment CDATA #REQUIRED>
<!ATTLIST Combine order (msb|lsb|copy) "lsb">

<!ELEMENT Bits (#PCDATA)>
<!ATTLIST Bits start CDATA #IMPLIED>


<!ELEMENT FieldName EMPTY>
<!ATTLIST FieldName name ID #REQUIRED>

<!ELEMENT xinclude:include EMPTY>
<!ATTLIST xinclude:include href CDATA #REQUIRED>

=== CloudlyIO/open-mplane/fb-oru/hardware/common/fpga/xml/ECB-features.xml
<?xml version="1.0"?>
<!DOCTYPE RegisterMap SYSTEM "../../../../fpga/registers/dtd/RegMap.dtd">
<RegisterMap version="1.0">

 	<Device name="FPGA">

 		<Feature name="Antenna" comment="Antenna registers">
			<xinclude:include  href="../../../../fpga/registers/xml/Antenna.xml#Antenna"/>
 		</Feature>

 		<Feature name="Chain" comment="Chain IQ registers">
			<xinclude:include  href="../../../../fpga/registers/xml/Chain.xml#Chain"/>
 		</Feature>

 		<Feature name="Fibre" comment="Fibre registers">
			<xinclude:include  href="../../../../fpga/registers/xml/Fibre.xml#Fibre"/>
 		</Feature>

 		<Feature name="Iq" comment="Fibre IQ registers">
			<xinclude:include  href="../../../../fpga/registers/xml/Iq.xml#Iq"/>
 		</Feature>

 		<Feature name="Msk" comment="MSK registers">
			<xinclude:include  href="../../../../fpga/registers/xml/Msk.xml#Msk"/>
 		</Feature>

 		<Feature name="System" comment="System registers">
			<xinclude:include  href="../../../../fpga/registers/xml/System.xml#System"/>
			<xinclude:include  href="../../../../fpga/registers/xml/System.xml#RF_Chain_Registers"/>
 		</Feature>

 		<Feature name="Tone" comment="Tone registers">
			<xinclude:include  href="../../../../fpga/registers/xml/Tone.xml#Tone"/>
 		</Feature>

 		<Feature name="Waveform" comment="Waveform registers">
			<xinclude:include  href="../../../../fpga/registers/xml/System.xml#SystemWaveform"/>
			<xinclude:include  href="../../../../fpga/registers/xml/Waveform.xml#Waveform"/>
 		</Feature>

	</Device>

</RegisterMap>
