=== CloudlyIO/open-mplane/fb-oru/hardware/common/caldata/gtest/config/padetcal.dtd
<!ELEMENT ECBCalibrationTx (TxPaCal+)>
<!ATTLIST ECBCalibrationTx version CDATA #REQUIRED>
<!ATTLIST ECBCalibrationTx country CDATA #IMPLIED>
<!ATTLIST ECBCalibrationTx facility CDATA #IMPLIED>
<!ATTLIST ECBCalibrationTx operator CDATA #IMPLIED>
<!ATTLIST ECBCalibrationTx xmlns:html CDATA "http://www.w3.org/TR/REC-html40">
<!ATTLIST ECBCalibrationTx xmlns:xinclude CDATA "http://www.w3.org/2001/XInclude">

<!ELEMENT TxPaCal (Path,Date,LinearTemperatureCompensation,FrequencyTable+)>
<!ATTLIST TxPaCal comment CDATA #IMPLIED>

<!ELEMENT Path (#PCDATA)*>
<!ELEMENT Version (#PCDATA)*>
<!ELEMENT Date (#PCDATA)*>

<!ELEMENT LinearTemperatureCompensation (Coefficient)>

<!ELEMENT Coefficient (#PCDATA)*>
<!ATTLIST Coefficient units CDATA #IMPLIED>

<!ELEMENT FrequencyTable (Frequency, Point+)>
<!ATTLIST FrequencyTable comment CDATA #IMPLIED>

<!ELEMENT Frequency (#PCDATA)>

<!ELEMENT Point (Power,PwrIn, DetADC)>

<!ELEMENT Power (#PCDATA)>

<!ELEMENT PwrIn (#PCDATA)>

<!ELEMENT DetADC (#PCDATA)>

<!ELEMENT xinclude:include EMPTY>
<!ATTLIST xinclude:include href CDATA #REQUIRED>

=== CloudlyIO/open-mplane/fb-oru/hardware/common/caldata/gtest/config/padetcal.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE calibration SYSTEM "padetcal.dtd">
<ECBCalibrationTx version="1" operator="HJS" facility="Harlow" country="UK">
	<TxPaCal comment="Padetcal for Europa-3 with incremental PwrIn fields added">
		<Path>1</Path>
		<Date>08/12/2016 11:10:39</Date>
		<LinearTemperatureCompensation>
			<!-- support for multiple methods i.e. linear, ploy, LUT. These are normally 
				fixed at design time against hardware revision from engineers logbook -->
			<!-- Requirement for temperature compensation To Be Confirmed -->
			<Coefficient units="DetADC/DegC">0.05</Coefficient>
		</LinearTemperatureCompensation>
		<FrequencyTable
			comment="Top 3 points of 1200 and 1800 MHz doctored for monotonicity, will be approxmate">
			<Frequency>700000</Frequency>
			<Point>
				<Power>48.00</Power>
				<PwrIn>-17.90</PwrIn>
				<DetADC>1326</DetADC>
			</Point>
			<Point>
				<Power>46.97</Power>
				<PwrIn>-19.19</PwrIn>
				<DetADC>1355</DetADC>
			</Point>
			<Point>
				<Power>46.00</Power>
				<PwrIn>-20.53</PwrIn>
				<DetADC>1388</DetADC>
			</Point>
			<Point>
				<Power>45.00</Power>
				<PwrIn>-21.96</PwrIn>
				<DetADC>1425</DetADC>
			</Point>
			<Point>
				<Power>40.02</Power>
				<PwrIn>-28.44</PwrIn>
				<DetADC>1635</DetADC>
			</Point>
			<Point>
				<Power>35.02</Power>
				<PwrIn>-34.36</PwrIn>
				<DetADC>1848</DetADC>
			</Point>
			<Point>
				<Power>30.00</Power>
				<PwrIn>-39.99</PwrIn>
				<DetADC>2059</DetADC>
			</Point>
			<Point>
				<Power>25.00</Power>
				<PwrIn>-45.25</PwrIn>
				<DetADC>2268</DetADC>
			</Point>
			<Point>
				<Power>20.02</Power>
				<PwrIn>-50.37</PwrIn>
				<DetADC>2477</DetADC>
			</Point>
			<Point>
				<Power>15.03</Power>
				<PwrIn>-55.02</PwrIn>
				<DetADC>2669</DetADC>
			</Point>
		</FrequencyTable>
		<FrequencyTable>
			<Frequency>1200000</Frequency>
			<Point>
				<Power>48.0</Power>
				<PwrIn>-17.0</PwrIn>
				<DetADC>1268</DetADC>
			</Point>
			<Point>
				<Power>47.0</Power>
				<PwrIn>-18.3</PwrIn>
				<DetADC>1311</DetADC>
			</Point>
			<Point>
				<Power>46.00</Power>
				<PwrIn>-19.59</PwrIn>
				<DetADC>1353</DetADC>
			</Point>
			<Point>
				<Power>45.00</Power>
				<PwrIn>-20.72</PwrIn>
				<DetADC>1392</DetADC>
			</Point>
			<Point>
				<Power>39.98</Power>
				<PwrIn>-26.56</PwrIn>
				<DetADC>1608</DetADC>
			</Point>
			<Point>
				<Power>35.00</Power>
				<PwrIn>-31.99</PwrIn>
				<DetADC>1818</DetADC>
			</Point>
			<Point>
				<Power>30.00</Power>
				<PwrIn>-37.40</PwrIn>
				<DetADC>2028</DetADC>
			</Point>
			<Point>
				<Power>25.00</Power>
				<PwrIn>-42.65</PwrIn>
				<DetADC>2234</DetADC>
			</Point>
			<Point>
				<Power>20.00</Power>
				<PwrIn>-47.69</PwrIn>
				<DetADC>2438</DetADC>
			</Point>
			<Point>
				<Power>15.00</Power>
				<PwrIn>-52.74</PwrIn>
				<DetADC>2640</DetADC>
			</Point>
		</FrequencyTable>
		<FrequencyTable>
			<Frequency>1800000</Frequency>
			<Point>
				<Power>48</Power>
				<PwrIn>-15.8</PwrIn>
				<DetADC>1390</DetADC>
			</Point>
			<Point>
				<Power>47.0</Power>
				<PwrIn>-17.3</PwrIn>
				<DetADC>1423</DetADC>
			</Point>
			<Point>
				<Power>46.0</Power>
				<PwrIn>-18.7</PwrIn>
				<DetADC>1458</DetADC>
			</Point>
			<Point>
				<Power>44.97</Power>
				<PwrIn>-20.16</PwrIn>
				<DetADC>1492</DetADC>
			</Point>
			<Point>
				<Power>40.00</Power>
				<PwrIn>-26.45</PwrIn>
				<DetADC>1656</DetADC>
			</Point>
			<Point>
				<Power>34.98</Power>
				<PwrIn>-32.26</PwrIn>
				<DetADC>1845</DetADC>
			</Point>
			<Point>
				<Power>30.00</Power>
				<PwrIn>-37.60</PwrIn>
				<DetADC>2044</DetADC>
			</Point>
			<Point>
				<Power>25.02</Power>
				<PwrIn>-42.73</PwrIn>
				<DetADC>2247</DetADC>
			</Point>
			<Point>
				<Power>20.00</Power>
				<PwrIn>-47.79</PwrIn>
				<DetADC>2450</DetADC>
			</Point>
			<Point>
				<Power>15.00</Power>
				<PwrIn>-52.72</PwrIn>
				<DetADC>2646</DetADC>
			</Point>
		</FrequencyTable>
		<FrequencyTable>
			<Frequency>2200000</Frequency>
			<Point>
				<Power>48.00</Power>
				<PwrIn>-15.87</PwrIn>
				<DetADC>1292</DetADC>
			</Point>
			<Point>
				<Power>47.00</Power>
				<PwrIn>-17.73</PwrIn>
				<DetADC>1338</DetADC>
			</Point>
			<Point>
				<Power>46.00</Power>
				<PwrIn>-19.25</PwrIn>
				<DetADC>1376</DetADC>
			</Point>
			<Point>
				<Power>45.00</Power>
				<PwrIn>-20.97</PwrIn>
				<DetADC>1420</DetADC>
			</Point>
			<Point>
				<Power>40.00</Power>
				<PwrIn>-28.93</PwrIn>
				<DetADC>1613</DetADC>
			</Point>
			<Point>
				<Power>35.00</Power>
				<PwrIn>-35.14</PwrIn>
				<DetADC>1805</DetADC>
			</Point>
			<Point>
				<Power>30.00</Power>
				<PwrIn>-40.75</PwrIn>
				<DetADC>2005</DetADC>
			</Point>
			<Point>
				<Power>24.98</Power>
				<PwrIn>-45.83</PwrIn>
				<DetADC>2206</DetADC>
			</Point>
			<Point>
				<Power>19.97</Power>
				<PwrIn>-50.82</PwrIn>
				<DetADC>2408</DetADC>
			</Point>
			<Point>
				<Power>15.00</Power>
				<PwrIn>-55.74</PwrIn>
				<DetADC>2605</DetADC>
			</Point>
		</FrequencyTable>
		<FrequencyTable>
			<Frequency>2700000</Frequency>
			<Point>
				<Power>47.89</Power>
				<PwrIn>-9.46</PwrIn>
				<DetADC>1317</DetADC>
			</Point>
			<Point>
				<Power>47.00</Power>
				<PwrIn>-11.55</PwrIn>
				<DetADC>1343</DetADC>
			</Point>
			<Point>
				<Power>46.00</Power>
				<PwrIn>-13.20</PwrIn>
				<DetADC>1376</DetADC>
			</Point>
			<Point>
				<Power>45.00</Power>
				<PwrIn>-14.55</PwrIn>
				<DetADC>1412</DetADC>
			</Point>
			<Point>
				<Power>40.00</Power>
				<PwrIn>-20.13</PwrIn>
				<DetADC>1608</DetADC>
			</Point>
			<Point>
				<Power>35.00</Power>
				<PwrIn>-25.37</PwrIn>
				<DetADC>1812</DetADC>
			</Point>
			<Point>
				<Power>30.02</Power>
				<PwrIn>-30.60</PwrIn>
				<DetADC>2017</DetADC>
			</Point>
			<Point>
				<Power>25.02</Power>
				<PwrIn>-35.65</PwrIn>
				<DetADC>2216</DetADC>
			</Point>
			<Point>
				<Power>19.97</Power>
				<PwrIn>-40.72</PwrIn>
				<DetADC>2417</DetADC>
			</Point>
			<Point>
				<Power>15.00</Power>
				<PwrIn>-45.69</PwrIn>
				<DetADC>2613</DetADC>
			</Point>
		</FrequencyTable>
	</TxPaCal>
	<TxPaCal comment="PA Calibration data for closed loop PCL power levelling">
		<Path>2</Path>
		<Date>08/12/2016 11:10:39</Date>
		<LinearTemperatureCompensation>
			<!-- support for multiple methods i.e. linear, ploy, LUT. These are normally 
				fixed at design time against hardware revision from engineers logbook -->
			<!-- Requirement for temperature compensation To Be Confirmed -->
			<Coefficient units="DetADC/DegC">0.05</Coefficient>
		</LinearTemperatureCompensation>
		<FrequencyTable>
			<Frequency>700000</Frequency>
			<Point>
				<Power>47.00</Power>
				<PwrIn>-13.99</PwrIn>
				<DetADC>1401</DetADC>
			</Point>
			<Point>
				<Power>36.98</Power>
				<PwrIn>-23.39</PwrIn>
				<DetADC>1801</DetADC>
			</Point>
			<Point>
				<Power>27.00</Power>
				<PwrIn>-32.84</PwrIn>
				<DetADC>2200</DetADC>
			</Point>
			<Point>
				<Power>17.00</Power>
				<PwrIn>-42.41</PwrIn>
				<DetADC>2600</DetADC>
			</Point>
			<Point>
				<Power>12.02</Power>
				<PwrIn>-52.48</PwrIn>
				<DetADC>2999</DetADC>
			</Point>
		</FrequencyTable>
		<FrequencyTable>
			<Frequency>1700000</Frequency>
			<Point>
				<Power>47.00</Power>
				<PwrIn>-12.55</PwrIn>
				<DetADC>1400</DetADC>
			</Point>
			<Point>
				<Power>36.98</Power>
				<PwrIn>-22.09</PwrIn>
				<DetADC>1801</DetADC>
			</Point>
			<Point>
				<Power>26.97</Power>
				<PwrIn>-31.76</PwrIn>
				<DetADC>2201</DetADC>
			</Point>
			<Point>
				<Power>16.98</Power>
				<PwrIn>-41.49</PwrIn>
				<DetADC>2600</DetADC>
			</Point>
			<Point>
				<Power>12.01</Power>
				<PwrIn>-51.74</PwrIn>
				<DetADC>2998</DetADC>
			</Point>
		</FrequencyTable>
		<FrequencyTable>
			<Frequency>2700000</Frequency>
			<Point>
				<Power>47.00</Power>
				<PwrIn>-11.13</PwrIn>
				<DetADC>1400</DetADC>
			</Point>
			<Point>
				<Power>37.00</Power>
				<PwrIn>-20.88</PwrIn>
				<DetADC>1800</DetADC>
			</Point>
			<Point>
				<Power>27.00</Power>
				<PwrIn>-30.73</PwrIn>
				<DetADC>2200</DetADC>
			</Point>
			<Point>
				<Power>17.00</Power>
				<PwrIn>-40.59</PwrIn>
				<DetADC>2600</DetADC>
			</Point>
			<Point>
				<Power>12.00</Power>
				<PwrIn>-50.95</PwrIn>
				<DetADC>3000</DetADC>
			</Point>
		</FrequencyTable>
	</TxPaCal>
</ECBCalibrationTx>
