=== CloudlyIO/open-mplane/fb-oru/tif-common/shared/dtd/Tif.dtd
<!ELEMENT TestInterface (xinclude:include|Setting|Board)*>
<!ATTLIST TestInterface version CDATA #REQUIRED>
<!ATTLIST TestInterface xmlns:html CDATA "http://www.w3.org/TR/REC-html40">
<!ATTLIST TestInterface xmlns:xinclude CDATA "http://www.w3.org/2001/XInclude">

<!ELEMENT Setting EMPTY>
<!ATTLIST Setting name ID #REQUIRED>
<!ATTLIST Setting type CDATA #IMPLIED>
<!ATTLIST Setting default CDATA #IMPLIED>
<!ATTLIST Setting comment CDATA #IMPLIED>

<!ELEMENT Board (xinclude:include|Setting|Device)*>
<!ATTLIST Board name CDATA #REQUIRED>

<!ELEMENT Device (Device|Setting|Variable|Function|xinclude:include)*>
<!ATTLIST Device name ID #REQUIRED>
<!ATTLIST Device path CDATA #IMPLIED>
<!ATTLIST Device comment CDATA #IMPLIED>

<!ELEMENT Function (Args?,Return?,Example?)>
<!ATTLIST Function name ID #REQUIRED>
<!ATTLIST Function comment CDATA #IMPLIED>

<!ELEMENT Variable (#PCDATA)>
<!ATTLIST Variable name ID #REQUIRED>
<!ATTLIST Variable type CDATA #REQUIRED>
<!ATTLIST Variable units CDATA #IMPLIED>
<!ATTLIST Variable access (read-write|write-only|read-only) "read-write">
<!ATTLIST Variable min CDATA #IMPLIED>
<!ATTLIST Variable max CDATA #IMPLIED>
<!ATTLIST Variable comment CDATA #IMPLIED>

<!ELEMENT Args (Data*,xinclude:include*)>

<!ELEMENT Return (Data*,xinclude:include*)>

<!ELEMENT Example (#PCDATA)>

<!ELEMENT Data (#PCDATA | xinclude:include)*>
<!ATTLIST Data type CDATA #REQUIRED>
<!ATTLIST Data units CDATA #IMPLIED>
<!ATTLIST Data comment CDATA #IMPLIED>
<!ATTLIST Data optional CDATA #IMPLIED>
<!ATTLIST Data default CDATA #IMPLIED>
<!ATTLIST Data min CDATA #IMPLIED>
<!ATTLIST Data max CDATA #IMPLIED>
<!ATTLIST Data step CDATA #IMPLIED>

<!ELEMENT xinclude:include EMPTY>
<!ATTLIST xinclude:include href CDATA #REQUIRED>

=== CloudlyIO/open-mplane/fb-oru/tif/helper/common/Model/gtest/test-xml/System.xml
<?xml version="1.0"?>
<!DOCTYPE TestInterface SYSTEM "../../../../../shared/dtd/Tif.dtd">
<TestInterface version="1.0">
	<Board name="Helper">
		<Device name="System" path="/system" comment="System information">
			<xinclude:include href="../../../../../helper/common/xml/System.xml#Version"/>
			<xinclude:include href="../../../../../helper/common/xml/System.xml#Build"/>
			<xinclude:include href="../../../../../helper/common/xml/System.xml#Customer"/>
			<xinclude:include href="../../../../../helper/common/xml/System.xml#Application"/>
			<xinclude:include href="../../../../../helper/common/xml/System.xml#Board"/>
			<xinclude:include href="../../../../../helper/common/xml/System.xml#Duplex"/>
			<xinclude:include href="../../../../../helper/common/xml/System.xml#FibreInterface"/>
			<xinclude:include href="../../../../../helper/common/xml/System.xml#CurrentFpgaBuild"/>
			<xinclude:include href="../../../../../helper/common/xml/System.xml#FpgaPart"/>
			<xinclude:include href="../../../../../helper/common/xml/System.xml#FpgaBuild"/>
			<xinclude:include href="../../../../../helper/common/xml/System.xml#ClockIn"/>
			<xinclude:include href="../../../../../helper/common/xml/System.xml#setClockIn"/>
			<xinclude:include href="../../../../../helper/common/xml/System.xml#services"/>
			<xinclude:include href="../../../../../helper/common/xml/System.xml#reboot"/>
			<xinclude:include href="../../../../../helper/common/xml/System.xml#gitVersions"/>
			<xinclude:include href="../../../../../helper/common/xml/System.xml#powerDown"/>
		</Device>
	</Board>
</TestInterface>

=== CloudlyIO/open-mplane/fb-oru/tif/helper/common/Model/gtest/test-xml/Carrier.xml
<?xml version="1.0"?>
<!DOCTYPE TestInterface SYSTEM "../../../../../shared/dtd/Tif.dtd">
<TestInterface version="1.0">
	<Board name="Helper">
		<Device name="Carrier" path="/carrier" comment="Common Carrier settings functions">
			<xinclude:include href="../../../../../helper/common/xml/Carrier.xml#NumCarriers"/>
			<xinclude:include href="../../../../../helper/common/xml/Carrier.xml#TxPaths"/>
			<xinclude:include href="../../../../../helper/common/xml/Carrier.xml#RxPaths"/>
			<xinclude:include href="../../../../../helper/common/xml/Carrier.xml#show"/>
			<xinclude:include href="../../../../../helper/common/xml/Carrier.xml#showAll"/>
			<xinclude:include href="../../../../../helper/common/xml/Carrier.xml#set"/>
			<xinclude:include href="../../../../../helper/common/xml/Carrier.xml#get"/>
		</Device>
	</Board>
</TestInterface>

=== CloudlyIO/open-mplane/fb-oru/tif/helper/common/Model/gtest/test-xml/BncCtl.xml
<?xml version="1.0"?>
<!DOCTYPE TestInterface SYSTEM "../../../../../shared/dtd/Tif.dtd">
<TestInterface version="1.0">
	<Board name="Helper">
		<Device name="BncCtl" path="/ref" comment="Common 10MHz control and status">			
			<xinclude:include href="../../../../../helper/common/xml/TenMHzRef.xml#setBncConfig"/>
			<xinclude:include href="../../../../../helper/common/xml/TenMHzRef.xml#getBncConfig"/>
			<xinclude:include href="../../../../../helper/common/xml/TenMHzRef.xml#setBnc1"/>
			<xinclude:include href="../../../../../helper/common/xml/TenMHzRef.xml#getBnc1"/>
			<xinclude:include href="../../../../../helper/common/xml/TenMHzRef.xml#setBnc2"/>
			<xinclude:include href="../../../../../helper/common/xml/TenMHzRef.xml#getBnc2"/>
			<xinclude:include href="../../../../../helper/common/xml/TenMHzRef.xml#setBnc3"/>
			<xinclude:include href="../../../../../helper/common/xml/TenMHzRef.xml#getBnc3"/>
			<xinclude:include href="../../../../../helper/common/xml/TenMHzRef.xml#setBnc4"/>
			<xinclude:include href="../../../../../helper/common/xml/TenMHzRef.xml#getBnc4"/>
			<xinclude:include href="../../../../../helper/common/xml/TenMHzRef.xml#setBnc5"/>
			<xinclude:include href="../../../../../helper/common/xml/TenMHzRef.xml#getBnc5"/>
			<xinclude:include href="../../../../../helper/common/xml/TenMHzRef.xml#setSyncOut"/>
			<xinclude:include href="../../../../../helper/common/xml/TenMHzRef.xml#getSyncOut"/>
			<xinclude:include href="../../../../../helper/common/xml/TenMHzRef.xml#setSyncIn"/>
			<xinclude:include href="../../../../../helper/common/xml/TenMHzRef.xml#getSyncIn"/>
		</Device>
	</Board>
</TestInterface>

=== CloudlyIO/open-mplane/fb-oru/tif/helper/common/Model/gtest/test-xml/Pim.xml
<?xml version="1.0"?>
<!DOCTYPE TestInterface SYSTEM "../../../../../shared/dtd/Tif.dtd">
<TestInterface version="1.0">
	<Board name="Helper">
		<Device name="Pim" path="/pim" comment="PIM control">
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#setCarriers"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#portOpen"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#portClose"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#portShow"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#logOpen"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#logClose"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#logShow"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#apiVersion"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#set"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#get"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#restart"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#search"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#initialSearch"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#dispersiveSearch"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#update"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#start"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#stop"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#startTssi"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#stopTssi"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#orthogonalise"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#pdp"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#avgPdp"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#enableStim"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#disableStim"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#dump"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#reset"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#runTest"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#frd"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#fwr"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#capture"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#getCoeffs"/>
			<xinclude:include href="../../../../../helper/common/xml/Pim.xml#xcorr"/>
		</Device>
	</Board>
</TestInterface>

=== CloudlyIO/open-mplane/fb-oru/tif/helper/common/xml/SystemCommon.xml
<?xml version="1.0"?>
<!DOCTYPE TestInterface SYSTEM "../../../shared/dtd/Tif.dtd">
<TestInterface version="1.0">
 	<Board name="common">
		<Device name="System" path="/system" comment="System information">

			<Variable name="Version" type="STRING" access="read-only" comment="Shows the application version string" />
			<Variable name="Build" type="INT" access="read-only" comment="Shows the build number" />
			<Variable name="Customer" type="STRING" access="read-only" comment="Shows the build customer string" />
			<Variable name="Application" type="STRING" access="read-only" comment="Shows the build application string" />
			<Variable name="Board" type="STRING" access="read-only" comment="Shows the build board string" />
			<Variable name="Duplex" type="STRING" access="read-only" comment="Shows the build duplex string" />
			<Variable name="FibreInterface" type="STRING" access="read-only" comment="Shows the build fibre interface string" />
            <Variable name="CurrentFpgaBuild" type="INT" access="read-only" comment="Shows the FPGA build number of the currently fitted FPGA" />
            <Variable name="FpgaPart" type="STRING" access="read-only" comment="Shows the FPGA part number the software was built with" />
            <Variable name="FpgaBuild" type="STRING" access="read-only" comment="Shows the FPGA build number the software was built with" />
            <Variable name="HwId" type="STRING" access="read-only" comment="Shows the hardware identification of the system" />
            <Variable name="HwRev" type="STRING" access="read-only" comment="Shows the hardware revision of the system" />

            <Function name="getBoardId" comment="Return the radio card board identification">
                <Return>
                    <Data type="INT">BoardID</Data>
                </Return>
            </Function>
			<Function name="services" comment="Allows all application services to be temporarily suspended and resumed">
                <Args>
                    <Data type="ENUM(suspend:resume)" comment="Request that all services are suspended or resumed">control</Data>
                </Args>
			</Function>

            <Function name="reboot" comment="Reboot the board" />
            
<!--
Removed from config.h - could be restored by creating a standalone file that the application reads in
 
            <Function name="gitVersions" comment="Show the git versions for this build" />
 -->
 
            <Function name="getSerialNumber" comment="Gets the serial number">
                <Return>
                    <Data type="STRING" comment="Serial Number">result</Data>
                </Return>
            </Function>

			<Function name="getHwBoardSerialNumber" comment="Gets the serial number">
				<Return>
					<Data type="STRING" comment="Hardware Board Serial Number">result</Data>
				</Return>
			</Function>
            
			<Function name="getHostName" comment="Gets the host name">

                <Return>
                    <Data type="STRING" comment="Host Name">result</Data>
                </Return>
            </Function>
            
            <Function name="getProductCode" comment="Gets the product code">
                <Return>
                    <Data type="STRING" comment="Product Number">result</Data>
                </Return>
            </Function>
            
            <Function name="showTasks" comment="Show task list" />
            <Function name="showLimits" comment="Show list of radio limits" />

            <Function name="getLimits" comment="Get list of radio limits" >
                <Return>
                    <Data type="INT" comment="Number of TX ports">numTx</Data>
                    <Data type="INT" comment="Number of RX ports">numRx</Data>
                    <Data type="INT" comment="Number of carriers">numCarriers</Data>
                    <Data type="INT" comment="Number of fibre ports">numFibres</Data>
                    <Data type="FLOAT[]" units="dB" comment="Min output power for each TX port">minPower</Data>
                    <Data type="FLOAT[]" units="dB" comment="Max output power for each TX port">maxPower</Data>
                    <Data type="FLOAT" units="kHz" comment="Min TX frequency">minTxFreq</Data>
                    <Data type="FLOAT" units="kHz" comment="Max TX frequency">maxTxFreq</Data>
                    <Data type="FLOAT" units="kHz" comment="Min RX frequency">minRxFreq</Data>
                    <Data type="FLOAT" units="kHz" comment="Max RX frequency">maxRxFreq</Data>
                </Return>
            </Function>

            <Function name="getSupplyVoltage" comment="Return the radio main supply voltage">
                <Return>
                    <Data type="FLOAT">value</Data>
                </Return>
            </Function>

			<Function name="getTemperature" comment="Retrieves the FPGA temperature">
			   <Return>
                    <Data type="FLOAT" units="DegC" comment="Temperature in Degrees Centigrade ">temperature</Data>
               </Return>
            </Function>

			<Function name="getState" comment="Show the application state">
			   <Return>
                    <Data type="ENUM(INITIALISING:STABLE:FAILED)" comment="Shows whether the application has reached the stable point or not">appState</Data>
               </Return>
            </Function>          
            
            <Function name="getDuplex" comment="Get duplex setting">        
                <Return>
                    <Data type="STRING" comment="Return the duplex setting">duplex</Data>
                </Return>
            </Function> 

            <Function name="setDateTime" comment="Sets the radio date and time in the form YYYY-MM-DD hh:mm:ss">
                <Args>
                    <Data type="STRING" comment="Date in the form YYYY-MM-DD">date</Data>
                    <Data type="STRING" comment="Time in the form hh:mm:ss">time</Data>
                </Args>
            </Function>
            
            <Function name="getDateTime" comment="Gets the radio date and time in the form YYYY-MM-DD hh:mm:ss">        
                <Return>
                    <Data type="STRING" comment="Date/Time in the form YYYY-MM-DD hh:mm:ss">dateTime</Data>
                </Return>
            </Function> 

		</Device>

	</Board>
</TestInterface>

=== CloudlyIO/open-mplane/fb-oru/tif-common/helper/common/xml/Discovery.xml
<?xml version="1.0"?>
<!DOCTYPE TestInterface SYSTEM "../../../shared/dtd/Tif.dtd">
<TestInterface version="1.0">
 	<Board name="common">

		<Device name="Discovery" path="/discovery" comment="Network discovery statistics">

			<Variable name="ip" type="STRING" access="read-only" comment="IP Address" />
			<Variable name="uuid" type="STRING" access="read-only" comment="SSDP uuid" />
			<Variable name="cacheAge" type="INT" units="S" access="read-only" comment="Maximum time between notifications" />
			<Variable name="searchCount" type="INT" access="read-only" comment="Number of search requests since connection" />
			<Variable name="notifyCount" type="INT" access="read-only" comment="Number of notifications sent since connection" />

		</Device>

	</Board>
</TestInterface>

=== CloudlyIO/open-mplane/fb-oru/tif/helper/common/Model/gtest/test-xml/Dpd.xml
<?xml version="1.0"?>
<!DOCTYPE TestInterface SYSTEM "../../../../../shared/dtd/Tif.dtd">
<TestInterface version="1.0">
	<Board name="Helper">
		<Device name="Dpd" path="/dpd" comment="DPD control">
			<xinclude:include href="../../../../../helper/common/xml/Dpd.xml#portOpen"/>
			<xinclude:include href="../../../../../helper/common/xml/Dpd.xml#portClose"/>
			<xinclude:include href="../../../../../helper/common/xml/Dpd.xml#logOpen"/>
			<xinclude:include href="../../../../../helper/common/xml/Dpd.xml#logClose"/>
			<xinclude:include href="../../../../../helper/common/xml/Dpd.xml#apiVersion"/>
			<xinclude:include href="../../../../../helper/common/xml/Dpd.xml#set"/>
			<xinclude:include href="../../../../../helper/common/xml/Dpd.xml#get"/>
			<xinclude:include href="../../../../../helper/common/xml/Dpd.xml#reboot"/>
			<xinclude:include href="../../../../../helper/common/xml/Dpd.xml#reset"/>
			<xinclude:include href="../../../../../helper/common/xml/Dpd.xml#frd"/>
			<xinclude:include href="../../../../../helper/common/xml/Dpd.xml#fwr"/>
			<xinclude:include href="../../../../../helper/common/xml/Dpd.xml#dumpFpga"/>
			<xinclude:include href="../../../../../helper/common/xml/Dpd.xml#dumpLuts"/>
			<xinclude:include href="../../../../../helper/common/xml/Dpd.xml#runTest"/>
			<xinclude:include href="../../../../../helper/common/xml/Dpd.xml#capture"/>
		</Device>
	</Board>
</TestInterface>

=== CloudlyIO/open-mplane/fb-oru/tif/helper/common/Model/gtest/test-xml/Fpga.xml
<?xml version="1.0"?>
<!DOCTYPE TestInterface SYSTEM "../../../../../shared/dtd/Tif.dtd">
<TestInterface version="1.0">
	<Board name="Helper">
		<Device name="Fpga" path="/fpga" comment="FPGA device">
			<xinclude:include href="../../../../../helper/common/xml/Fpga.xml#read"/>
			<xinclude:include href="../../../../../helper/common/xml/Fpga.xml#write"/>
			<xinclude:include href="../../../../../helper/common/xml/Fpga.xml#monitor"/>
			<xinclude:include href="../../../../../helper/common/xml/Fpga.xml#monitorShow"/>
			<xinclude:include href="../../../../../helper/common/xml/Fpga.xml#getTemperature"/>
			<xinclude:include href="../../../../../helper/common/xml/Fpga.xml#modify"/>
		</Device>
	</Board>
</TestInterface>
