=== CloudlyIO/open-mplane/fb-oru/tif-common/shared/dtd/Tif.dtd
<!ELEMENT TestInterface (xinclude:include|Setting|Board)*>
<!ATTLIST TestInterface version CDATA #REQUIRED>
<!ATTLIST TestInterface xmlns:html CDATA "http://www.w3.org/TR/REC-html40">
<!ATTLIST TestInterface xmlns:xinclude CDATA "http://www.w3.org/2001/XInclude">

<!ELEMENT Setting EMPTY>
<!ATTLIST Setting name ID #REQUIRED>
<!ATTLIST Setting type CDATA #IMPLIED>
<!ATTLIST Setting default CDATA #IMPLIED>
<!ATTLIST Setting comment CDATA #IMPLIED>

<!ELEMENT Board (xinclude:include|Setting|Device)*>
<!ATTLIST Board name CDATA #REQUIRED>

<!ELEMENT Device (Device|Setting|Variable|Function|xinclude:include)*>
<!ATTLIST Device name ID #REQUIRED>
<!ATTLIST Device path CDATA #IMPLIED>
<!ATTLIST Device comment CDATA #IMPLIED>

<!ELEMENT Function (Args?,Return?,Example?)>
<!ATTLIST Function name ID #REQUIRED>
<!ATTLIST Function comment CDATA #IMPLIED>

<!ELEMENT Variable (#PCDATA)>
<!ATTLIST Variable name ID #REQUIRED>
<!ATTLIST Variable type CDATA #REQUIRED>
<!ATTLIST Variable units CDATA #IMPLIED>
<!ATTLIST Variable access (read-write|write-only|read-only) "read-write">
<!ATTLIST Variable min CDATA #IMPLIED>
<!ATTLIST Variable max CDATA #IMPLIED>
<!ATTLIST Variable comment CDATA #IMPLIED>

<!ELEMENT Args (Data*,xinclude:include*)>

<!ELEMENT Return (Data*,xinclude:include*)>

<!ELEMENT Example (#PCDATA)>

<!ELEMENT Data (#PCDATA | xinclude:include)*>
<!ATTLIST Data type CDATA #REQUIRED>
<!ATTLIST Data units CDATA #IMPLIED>
<!ATTLIST Data comment CDATA #IMPLIED>
<!ATTLIST Data optional CDATA #IMPLIED>
<!ATTLIST Data default CDATA #IMPLIED>
<!ATTLIST Data min CDATA #IMPLIED>
<!ATTLIST Data max CDATA #IMPLIED>
<!ATTLIST Data step CDATA #IMPLIED>

<!ELEMENT xinclude:include EMPTY>
<!ATTLIST xinclude:include href CDATA #REQUIRED>

=== CloudlyIO/open-mplane/fb-oru/tif/helper/common/Model/gtest/test-xml/Images.xml
<?xml version="1.0"?>
<!DOCTYPE TestInterface SYSTEM "../../../../../shared/dtd/Tif.dtd">
<TestInterface version="1.0">
	<Board name="Helper">
		<Device name="Images" path="/image" comment="Image Management settings">
			<xinclude:include href="../../../../../helper/common/xml/Images.xml#url"/>
			<xinclude:include href="../../../../../helper/common/xml/Images.xml#bank"/>
			<xinclude:include href="../../../../../helper/common/xml/Images.xml#uboot"/>
			<xinclude:include href="../../../../../helper/common/xml/Images.xml#install"/>
			<xinclude:include href="../../../../../helper/common/xml/Images.xml#installFile"/>
			<xinclude:include href="../../../../../helper/common/xml/Images.xml#show"/>
			<xinclude:include href="../../../../../helper/common/xml/Images.xml#showDetail"/>
			<xinclude:include href="../../../../../helper/common/xml/Images.xml#clean"/>
		</Device>
	</Board>
</TestInterface>

=== CloudlyIO/open-mplane/fb-oru/tif/helper/common/Model/gtest/test-xml/SPI.xml
<?xml version="1.0"?>
<!DOCTYPE TestInterface SYSTEM "../../../../../shared/dtd/Tif.dtd">
<TestInterface version="1.0">
	<Board name="Helper">
		<Device name="SPI" path="/.spi" comment="Generic SPI interface">
			<xinclude:include href="../../../../../helper/common/xml/SPI.xml#get"/>
			<xinclude:include href="../../../../../helper/common/xml/SPI.xml#set"/>
			<xinclude:include href="../../../../../helper/common/xml/SPI.xml#read"/>
			<xinclude:include href="../../../../../helper/common/xml/SPI.xml#write"/>
			<xinclude:include href="../../../../../helper/common/xml/SPI.xml#lock"/>
			<xinclude:include href="../../../../../helper/common/xml/SPI.xml#unlock"/>
			<xinclude:include href="../../../../../helper/common/xml/SPI.xml#setbus"/>
		</Device>
	</Board>
</TestInterface>

=== CloudlyIO/open-mplane/fb-oru/tif/helper/common/Model/gtest/test-xml/TenMHzRef.xml
<?xml version="1.0"?>
<!DOCTYPE TestInterface SYSTEM "../../../../../shared/dtd/Tif.dtd">
<TestInterface version="1.0">
	<Board name="Helper">
		<Device name="TenMHzRef" path="/ref" comment="Common 10MHz control and status">			
			<xinclude:include href="../../../../../helper/common/xml/TenMHzRef.xml#getPresent"/>
			<xinclude:include href="../../../../../helper/common/xml/TenMHzRef.xml#getMode"/>
			<xinclude:include href="../../../../../helper/common/xml/TenMHzRef.xml#setMode"/>
			<xinclude:include href="../../../../../helper/common/xml/TenMHzRef.xml#getManualMode"/>
			<xinclude:include href="../../../../../helper/common/xml/TenMHzRef.xml#setManualMode"/>
		</Device>
	</Board>
</TestInterface>

=== CloudlyIO/open-mplane/fb-oru/tif/ZCU111-MPLANE-ORANRRH/Model/xml/Zcu111-Mplane-Oran-Rrh-TxPort.xml
<?xml version="1.0"?>
<!DOCTYPE TestInterface SYSTEM "../../../shared/dtd/Tif.dtd">
<TestInterface version="1.0">
 	<Board name="ZCU111-MPLANE-ORANRRH">
		<Device name="TxPort" path="/tx" comment="Tx Port settings">
		<xinclude:include href="../../../helper/common/xml/CommonSettings.xml#NUM_TX_PORTS"/>
		<xinclude:include href="../../../helper/common/xml/TxPort.xml#Ports"/>
		<xinclude:include href="../../../helper/common/xml/TxPort.xml#getFreq"/>
		<xinclude:include href="../../../helper/common/xml/TxPort.xml#setFreq"/>
		<xinclude:include href="../../../helper/common/xml/TxPort.xml#showSynth"/>
		<xinclude:include href="../../../helper/common/xml/TxPort.xml#getTemp"/>
		<xinclude:include href="../../../helper/common/xml/TxPort.xml#getAtten"/>
		<xinclude:include href="../../../helper/common/xml/TxPort.xml#setAtten"/>
		<xinclude:include href="../../../helper/common/xml/TxPort.xml#getScaler"/>
		<xinclude:include href="../../../helper/common/xml/TxPort.xml#setScaler"/>
		<xinclude:include href="../../../helper/common/xml/TxPort.xml#getCWPower"/>
		<xinclude:include href="../../../helper/common/xml/TxPort.xml#setCWPower"/>
		<xinclude:include href="../../../helper/common/xml/TxPort.xml#getFwdPower"/>
		<xinclude:include href="../../../helper/common/xml/TxPort.xml#getRevPower"/>
		<xinclude:include href="../../../helper/common/xml/TxPort.xml#setMode"/>
		<xinclude:include href="../../../helper/common/xml/TxPort.xml#setEnable"/>
		</Device>
	</Board>
</TestInterface>

=== CloudlyIO/open-mplane/fb-oru/tif/helper/common/Model/gtest/test-xml/Cpri.xml
<?xml version="1.0"?>
<!DOCTYPE TestInterface SYSTEM "../../../../../shared/dtd/Tif.dtd">
<TestInterface version="1.0">
	<Board name="Helper">
		<Device name="Cpri" path="/cpri" comment="CPRI Interface functions">
			<xinclude:include href="../../../../../helper/common/xml/Cpri.xml#NumPorts"/>
			<xinclude:include href="../../../../../helper/common/xml/Cpri.xml#showPort"/>
			<xinclude:include href="../../../../../helper/common/xml/Cpri.xml#showCtl"/>
			<xinclude:include href="../../../../../helper/common/xml/Cpri.xml#showAll"/>
			<xinclude:include href="../../../../../helper/common/xml/Cpri.xml#set"/>
			<xinclude:include href="../../../../../helper/common/xml/Cpri.xml#get"/>
		</Device>
	</Board>
</TestInterface>
